const config = {
  variables: {},
  colors: {
    // punolite plus palette
    "rabbit-ear-iris": "#431c3f",
    "burlat-red": "#6d324e",
    "lingonberry-punch": "#a65658",
    "pompeian-pink": "#c57763",
    "pecan-veneer": "#de9d75",
    "straw-yellow": "#f0d898",
    "pollen": "#eef3aa",
    "washed-out-green": "#bef3aa",
    "spring-bouquet": "#69c886",
    "laurel-wreath": "#50aa82",
    "greensleeves": "#3d766d",
    "atlantic-deep": "#294e58",
    "midnight-jam": "#06041b",
    "tetsu-kon-blue": "#101b4c",
    "assault": "#1e4676",
    "greenland-blue": "#377d99",
    "veranda-blue": "#61b6b1",
    "apple-2-blue": "#90d5bf",
    "mint-tulip": "#c7eada",
    "blue-angora": "#aacec8",
    "lap-pool-blue": "#96b9b9",
    "stone-blue": "#809da4",
    "space-convoy": "#647789",
    "extreme": "#535d76",
    "magic-night": "#3b3c58",
    "vapor": "#f2fffe",
  },
  fonts: [],
  mediaQueries: {
    su: "screen and (min-width: 1rem)",
    so: "screen and (max-width: 39.9375rem)",
    mu: "screen and (min-width: 40rem)",
    mo: "screen and (min-width: 40rem) and (max-width: 63.9375rem)",
    lu: "screen and (min-width: 64rem)",
    lo: "screen and (min-width: 64rem) and (max-width: 74.9375rem)",
  },
  body: {},
  headings: [],
  margins: {
    0: '0px',
    1: '.25rem',
    2: '.5rem',
    3: '1rem',
    4: '1.5rem',
    5: '2rem',
    6: '2.5rem',
    7: '3rem',
    8: '4rem',
    9: '5rem',
  },
  paddings: {
    0: '0px',
    1: '.25rem',
    2: '.5rem',
    3: '1rem',
    4: '1.5rem',
    5: '2rem',
    6: '2.5rem',
    7: '3rem',
    8: '4rem',
    9: '5rem',
  },
  borders: [],
  gaps: {
    1: '1rem',
    2: '2rem',
    3: '3rem',
  },
};

module.exports = {
  path: "src/playground/css",
  filename: "horizon-styles.css",
  docPath: "docs/styles/site",
  config,
};
